export interface DetailedKPI {
  id: string;
  category: 'Sản lượng' | 'Nhân sự' | 'Chi phí bộ phận' | '6S, Cải tiến' | 'Báo cáo kế hoạch' | 'Chất lượng NCC' | 'IQC - Chất lượng đầu vào' | 'PQC - Chất lượng quá trình' | 'OQC - Chất lượng đầu ra' | 'Hệ thống & Hồ sơ';
  type: 'Mục tiêu hoạt động chung' | 'Mục tiêu hoạt động chuyên môn';
  groupWeight: number; // Trọng số nhóm: e.g. 10%, 5%, 20%
  indicator: string;   // Tên chỉ tiêu
  definition: string;  // Định nghĩa
  unit: string;        // Đơn vị tính
  target: string;      // Mục tiêu đề ra
  actual: string;      // Thực tế đạt được
  status: 'Đạt' | 'Không đạt' | 'Đang cải tiến' | 'Theo dõi';
  details?: string;    // Chi tiết bổ sung
  month?: number;      // Tháng áp dụng chỉ tiêu (e.g. 5 cho tháng 5)
  year?: number;       // Năm áp dụng chỉ tiêu (e.g. 2026 cho năm 2026)
}

export const DEFAULT_DETAILED_KPIS: DetailedKPI[] = [
  // === MỤC TIÊU HOẠT ĐỘNG CHUNG (35%) ===
  // 1. Sản lượng (10%)
  {
    id: 'KPI-GEN-01',
    category: 'Sản lượng',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Số lượng kinh doanh',
    definition: 'Là sản lượng xe bán ra thị trường',
    unit: 'Xe',
    target: '50.000',
    actual: '48.500',
    status: 'Theo dõi',
    details: 'Sản lượng bán hàng lũy kế đang bám sát mục tiêu năm 2026.'
  },
  {
    id: 'KPI-GEN-02',
    category: 'Sản lượng',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Số lượng xe lắp ráp',
    definition: 'Là số lượng xe hoàn thiện đủ điều kiện xuất xưởng',
    unit: 'Xe',
    target: '50.174',
    actual: '50.174',
    status: 'Đạt',
    details: 'Đã xuất xưởng đủ sản lượng được giao của kế hoạch xe máy điện.'
  },
  // 2. Hoạt động nhân sự (5%)
  {
    id: 'KPI-GEN-03',
    category: 'Nhân sự',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Tổng định biên nhân sự',
    definition: 'Định biên nhân sự tối ưu của bộ phận QLCL',
    unit: 'Nhân sự',
    target: '3',
    actual: '3',
    status: 'Đạt',
    details: 'Nhân sự gồm 1 Trưởng phòng, 1 IQC/Supplier QC, 1 OQC/Hệ thống.'
  },
  {
    id: 'KPI-GEN-04',
    category: 'Nhân sự',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Chất lượng năng lực P2',
    definition: 'Tỉ lệ đạt năng lực chuyên môn kĩ thuật P2 trung bình của bộ phận',
    unit: 'Tỉ lệ %',
    target: '>90%',
    actual: '92%',
    status: 'Đạt',
    details: 'Đánh giá kỹ năng đo lường, rà soát FMEA và bóc hồ sơ kỹ thuật đạt chuẩn.'
  },
  {
    id: 'KPI-GEN-05',
    category: 'Nhân sự',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Chất lượng hiệu suất P3 Hằng tháng',
    definition: 'Hiệu suất kết quả công việc trung bình hằng tháng',
    unit: 'Tỉ lệ %',
    target: '>90%',
    actual: '91.8%',
    status: 'Đạt',
    details: 'Điểm KPI công việc của từng thành viên đạt bình quân trên 90 điểm.'
  },
  {
    id: 'KPI-GEN-06',
    category: 'Nhân sự',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Nội quy quy chế',
    definition: 'Số lần vi phạm Nội quy quy chế của Công ty',
    unit: 'Vi phạm',
    target: '0',
    actual: '0',
    status: 'Đạt',
    details: 'Tuân thủ nội quy tác phong công nghiệp, chấm công nghiêm túc.'
  },
  // 3. Chi phí bộ phận (10%)
  {
    id: 'KPI-GEN-07',
    category: 'Chi phí bộ phận',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Xây dựng kế hoạch chi phí bộ phận',
    definition: 'Định kỳ xây dựng kế hoạch chi phí, ngân sách bộ phận trình phê duyệt',
    unit: 'Tháng',
    target: '12',
    actual: '5',
    status: 'Theo dõi',
    details: 'Đã hoàn tất ngân sách và kế hoạch kiểm kê chi bộ phận định kỳ 5 tháng đầu năm.'
  },
  {
    id: 'KPI-GEN-08',
    category: 'Chi phí bộ phận',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Tỉ lệ chênh lệch chi phí',
    definition: 'Tỉ lệ chênh lệch chi phí bộ phận so với mục tiêu kế hoạch ngân sách',
    unit: '%',
    target: '<5%',
    actual: '2.8%',
    status: 'Đạt',
    details: 'Kiểm soát chi tiêu tiết kiệm, các danh mục đầu tư thiết bị mẫu đều đúng dự toán.'
  },
  {
    id: 'KPI-GEN-09',
    category: 'Chi phí bộ phận',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Theo dõi phân tích biến động chi phí',
    definition: 'Thực hiện ghi chép, tổng hợp chi phí bộ phận để phân tích lãng phí',
    unit: 'Lượt',
    target: '18',
    actual: '8',
    status: 'Theo dõi',
    details: 'Thực hiện phân tích chi tiết hiệu suất dùng xe công vụ, đi kiểm nhà thanh tra.'
  },
  {
    id: 'KPI-GEN-10',
    category: 'Chi phí bộ phận',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Tổng hợp theo dõi theo tháng',
    definition: 'Ghi nhận báo cáo chi phí phát sinh hàng tháng',
    unit: 'Tháng',
    target: '12',
    actual: '5',
    status: 'Theo dõi',
    details: 'Hồ sơ tài chính nội bộ lưu trữ khoa học đầy đủ.'
  },
  {
    id: 'KPI-GEN-11',
    category: 'Chi phí bộ phận',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Phân tích chi phí định kỳ',
    definition: 'Phân tích chi phí phát sinh định kỳ',
    unit: 'Quý',
    target: '4',
    actual: '1',
    status: 'Theo dõi',
    details: 'Báo cáo tài chính quý I đã nộp lãnh đạo kiểm duyệt.'
  },
  {
    id: 'KPI-GEN-12',
    category: 'Chi phí bộ phận',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Đánh giá sử dụng chi phí theo định mức',
    definition: 'Kiểm tra sử dụng chi phí so với hạn mức thực tế đầu người',
    unit: '6 tháng/Lần',
    target: '2',
    actual: '1',
    status: 'Theo dõi',
    details: 'Đã hoàn thành đánh giá kỳ I đúng tiến độ vào tháng 5/2026.'
  },
  {
    id: 'KPI-GEN-13',
    category: 'Chi phí bộ phận',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 10,
    indicator: 'Tiết kiệm chi phí hành chính',
    definition: 'Tỉ lệ tiết kiệm được ngân sách hành chính nhờ cải tiến, sáng kiến số hóa',
    unit: 'Tỉ lệ %',
    target: '>3%',
    actual: '4.5%',
    status: 'Đạt',
    details: 'Đưua vào áp dụng hệ thống Báo cáo tuần chất lượng số hóa giúp giảm in ấn giấy tờ.'
  },
  // 4. Hoạt động 6S, Cải tiến (5%)
  {
    id: 'KPI-GEN-14',
    category: '6S, Cải tiến',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Thực hiện duy trì 6S hằng ngày',
    definition: 'Tỉ lệ tuân thủ thực hiện 6S tại văn phòng, phòng thiết bị đo đạc hằng ngày',
    unit: 'Tỉ lệ %',
    target: '100%',
    actual: '100%',
    status: 'Đạt',
    details: 'Vệ sinh và bảo quản dụng cụ dưỡng kiểm, panme, thước cặp đúng vị trí phân bố.'
  },
  {
    id: 'KPI-GEN-15',
    category: '6S, Cải tiến',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Chấm điểm, đánh giá 6S định kì',
    definition: 'Thực hiện chấm chéo đánh giá 6S định kỳ hằng tháng',
    unit: 'Tháng',
    target: '12',
    actual: '5',
    status: 'Theo dõi',
    details: 'Duy trì tham gia chấm chéo cùng ban 6S nhà máy hàng tuần/tháng đầy đủ.'
  },
  {
    id: 'KPI-GEN-16',
    category: '6S, Cải tiến',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Điểm kiểm tra 6S bộ phận',
    definition: 'Số điểm đạt được khảo sát trên Thang 5. Điểm mục tiêu từ 4 trở lên',
    unit: 'Điểm',
    target: '4',
    actual: '4.2',
    status: 'Đạt',
    details: 'Ghi nhận xếp hạng Xuất sắc trong khối gián tiếp phụ trợ sản xuất.'
  },
  {
    id: 'KPI-GEN-17',
    category: '6S, Cải tiến',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Xử lý triệt để phát sinh 6S',
    definition: 'Số lượng phát hiện không phù hợp 6S được dọn dẹp vệ sinh xử lý ngay',
    unit: 'Tỉ lệ',
    target: '1.0',
    actual: '1.0',
    status: 'Đạt',
    details: 'Cam kết 100% điểm lỗi nhắc nhở được chụp hình khắc phục trước khi ra về.'
  },
  {
    id: 'KPI-GEN-18',
    category: '6S, Cải tiến',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Thời lượng xử lý vấn đề 6S',
    definition: 'Thời lượng xử lý các vấn đề 6S phát sinh không quá 8 tiếng từ lúc phát hiện',
    unit: 'Giờ',
    target: '<8 giờ',
    actual: '3.5 giờ',
    status: 'Đạt',
    details: 'Chấn chỉnh gán nhãn, dán cảnh báo khu vực máy đo 3D nhanh gọn.'
  },
  // 5. Báo cáo kế hoạch (5%)
  {
    id: 'KPI-GEN-19',
    category: 'Báo cáo kế hoạch',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Báo báo kế hoạch Tuần',
    definition: 'Thực hiện xây dựng và gửi báo cáo tuần trực tuyến đúng tiến độ công ty',
    unit: 'Báo cáo',
    target: '108',
    actual: '44',
    status: 'Theo dõi',
    details: 'Nộp báo cáo đầy đủ của tất cả các tuần từ đầu năm.'
  },
  {
    id: 'KPI-GEN-20',
    category: 'Báo cáo kế hoạch',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Báo cáo kế hoạch Tháng',
    definition: 'Hoàn thành và trình duyệt báo cáo tổng kết tháng đúng hạn',
    unit: 'Báo cáo',
    target: '24',
    actual: '10',
    status: 'Theo dõi',
    details: 'Đã hoàn thành bàn giao hồ sơ chất lượng gối đầu từng tháng.'
  },
  {
    id: 'KPI-GEN-21',
    category: 'Báo cáo kế hoạch',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Báo cáo kế hoạch Quý',
    definition: 'Xây dựng thông số tổng kiểm chất lượng theo quý gửi BGĐ',
    unit: 'Báo cáo',
    target: '8',
    actual: '3',
    status: 'Theo dõi',
    details: 'Đã nộp báo cáo rà soát CAPA quý I/2026.'
  },
  {
    id: 'KPI-GEN-22',
    category: 'Báo cáo kế hoạch',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Báo cáo kế hoạch Năm',
    definition: 'Xây dựng chiến lược chất lượng, định hướng chuyển đổi phòng ban',
    unit: 'Báo cáo',
    target: '5',
    actual: '1',
    status: 'Theo dõi',
    details: 'Kế hoạch định hướng năm đã thông qua Đại hội chỉ tiêu 2026.'
  },
  {
    id: 'KPI-GEN-23',
    category: 'Báo cáo kế hoạch',
    type: 'Mục tiêu hoạt động chung',
    groupWeight: 5,
    indicator: 'Chất lượng thông tin báo cáo',
    definition: 'Đầy đủ thông tin đầu việc, hướng dẫn, tiến độ, thời hạn rõ ràng',
    unit: 'Tỉ lệ %',
    target: '>90%',
    actual: '95%',
    status: 'Đạt',
    details: 'Báo cáo số luôn có biểu đồ và dữ liệu dẫn chứng rõ ràng.'
  },

  // === MỤC TIÊU HOẠT ĐỘNG CHUYÊN MÔN (65%) ===
  // 1. Chất lượng NCC (5%)
  {
    id: 'KPI-PRO-01',
    category: 'Chất lượng NCC',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 5,
    indicator: 'Đánh giá NCC Định kỳ',
    definition: 'Phối hợp với phòng Cung ứng đánh giá năng lực nhà cung cấp định kỳ (6 tháng/lần)',
    unit: 'Nhà cc',
    target: '9',
    actual: '5',
    status: 'Theo dõi',
    details: 'Đã khảo sát đánh giá thực tế năng lực gia công nhựa và lốp của 5 nhà cung cấp đợt I.'
  },
  {
    id: 'KPI-PRO-02',
    category: 'Chất lượng NCC',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 5,
    indicator: 'Tần suất thanh tra, kiểm định',
    definition: 'Rà soát và thanh tra đột xuất điều kiện sản xuất tại đối tác định kỳ',
    unit: 'Tháng',
    target: '2 tháng/Lần',
    actual: '2 tháng/Lần',
    status: 'Đạt',
    details: 'Đã cử kỹ sư hiện trường hỗ trợ xử lý móng nhiệt tại NCC xi mạ nhựa bửng.'
  },
  {
    id: 'KPI-PRO-03',
    category: 'Chất lượng NCC',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 5,
    indicator: 'Họp trao đổi kỹ thuật chất lượng',
    definition: 'Tổ chức họp mặt trao đổi cải tiến chất lượng sản phẩm định kỳ hàng tháng',
    unit: 'Nhà cc',
    target: '9',
    actual: '8',
    status: 'Đạt',
    details: 'Trực tiếp chất vấn KPI PPM lỗi cao su với Công ty KENDA và nhựa đúc Việt Nhật Precision.'
  },
  // 2. IQC - Chất lượng đầu vào (20%)
  {
    id: 'KPI-PRO-04',
    category: 'IQC - Chất lượng đầu vào',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 20,
    indicator: 'Số lệnh kiểm định tại xưởng NCC',
    definition: 'Thực hiện kiểm soát sau đặt hàng, trong chế tạo và trước khi đối tác giao về DK',
    unit: 'Tỉ lệ %',
    target: '100%',
    actual: '100%',
    status: 'Đạt',
    details: 'Triển khai chặt chẽ quy chế COA/QA kiểm tra trước khi chuyển xưởng.'
  },
  {
    id: 'KPI-PRO-05',
    category: 'IQC - Chất lượng đầu vào',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 20,
    indicator: 'Tần suất kiểm đầu vào kho DK',
    definition: 'Tỉ lệ các lô linh kiện đầu vào được kiểm nhập kích thước dán nhãn trước khi nhập kho',
    unit: 'Tỉ lệ %',
    target: '100%',
    actual: '100%',
    status: 'Đạt',
    details: '100% hàng hóa linh kiện về bến bãi nhà máy đều bắt buộc qua phòng dưỡng kiểm duyệt.'
  },
  {
    id: 'KPI-PRO-06',
    category: 'IQC - Chất lượng đầu vào',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 20,
    indicator: 'Tỷ lệ linh kiện đạt lần 1',
    definition: 'Tỉ lệ linh kiện đạt chất lượng ngay lần kiểm ráp đầu tiên không cần hoàn trả sửa đổi',
    unit: 'Tỉ lệ %',
    target: '>97%',
    actual: '96.2%',
    status: 'Không đạt',
    details: 'Còn vướng nhiều lô linh kiện lốp xe KENDA bị phồng bọc mủ lót ngoài và ốc gá bửng loang màu xi.'
  },
  {
    id: 'KPI-PRO-07',
    category: 'IQC - Chất lượng đầu vào',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 20,
    indicator: 'Tỉ lệ trích mẫu kiểm tra chi tiết lỗi',
    definition: 'Số lượng mẫu trích xuất kiểm định / Tổng quy cách linh kiện nhập lẻ của lô hàng',
    unit: 'Tỉ lệ %',
    target: '>10%',
    actual: '12%',
    status: 'Đạt',
    details: 'Thực hiện trích ly mẫu đo kiểm theo phương thức quy đổi AQL tiêu chuẩn MIL-STD-105D.'
  },
  {
    id: 'KPI-PRO-08',
    category: 'IQC - Chất lượng đầu vào',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 20,
    indicator: 'Tỷ lệ lỗi chất lượng nghiêm trọng đầu vào',
    definition: 'Khuyết tật ảnh hưởng trực tiếp đến an toàn lái xe, kết cấu chính (Mục tiêu bắt buộc bằng 0)',
    unit: 'Tỉ lệ %',
    target: '0%',
    actual: '0%',
    status: 'Đạt',
    details: 'Chưa phát hiện lỗi nghiêm trọng liên quan đến khung gầm sườn và IC điện chính.'
  },
  // 3. PQC - Chất lượng quá trình (10%)
  {
    id: 'KPI-PRO-09',
    category: 'PQC - Chất lượng quá trình',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 10,
    indicator: 'Kiểm tra linh kiện trước khi cấp lên chuyền',
    definition: 'Tuyển lọc và kiểm soát trạng thái linh kiện chuẩn bị tại gá trung chuyển lắp ráp',
    unit: 'Tỉ lệ',
    target: '>90%',
    actual: '93.5%',
    status: 'Đạt',
    details: 'Xử lý gác rổ chứa phụ tùng rơ-le định vị dây điện để tổ trưởng lắp ráp nhận diện nhanh.'
  },
  {
    id: 'KPI-PRO-10',
    category: 'PQC - Chất lượng quá trình',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 10,
    indicator: 'Tỷ lệ lỗi lọt trên băng chuyền',
    definition: 'Linh kiện lỗi chưa qua IQC phát hiện lọt vào chuyền gây nghẽn công đoạn sản xuất',
    unit: 'Tỉ lệ',
    target: '< 2%',
    actual: '1.4%',
    status: 'Đạt',
    details: 'Kiểm soát chặt chẽ giúp hạn chế dừng chuyền lắp ráp không đáng có.'
  },
  {
    id: 'KPI-PRO-11',
    category: 'PQC - Chất lượng quá trình',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 10,
    indicator: 'Kiểm tra túc trực lắp ráp',
    definition: 'Túc trực kiểm tra 4 công đoạn chính trên mỗi Lệnh sản xuất (Mỗi công đoạn đo 5 lượt)',
    unit: 'Lượt/LSX',
    target: '20',
    actual: '20',
    status: 'Đạt',
    details: 'Rà soát bám sát xiết lực cổ phốt, lực siết bánh trước sau và giác đi dây điện sườn xe.'
  },
  {
    id: 'KPI-PRO-12',
    category: 'PQC - Chất lượng quá trình',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 10,
    indicator: 'Thời gian dừng chuyền do sự cố chất lượng',
    definition: 'Thời lượng dây chuyền phải ngừng máy chờ khắc phục phế phẩm hỏng trên ca',
    unit: 'Phút',
    target: '<15p/ca',
    actual: '7 phút',
    status: 'Đạt',
    details: 'Phản ứng nhanh khắc phục bavia ổ gá sạc của model DK V1 giúp tiếp tục thông dây xưởng.'
  },
  {
    id: 'KPI-PRO-13',
    category: 'PQC - Chất lượng quá trình',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 10,
    indicator: 'Xử lý hành động CAPA đúng hạn',
    definition: 'Hoàn thành báo cáo phòng ngừa lỗi lặp lại đúng kỳ hạn thỏa thuận',
    unit: 'Tỉ lệ %',
    target: '>=95%',
    actual: '96.8%',
    status: 'Đạt',
    details: 'Tất cả các phòng Kỹ thuật và Sản xuất đã phối hợp rà soát đóng hồ sơ CAPA nhanh chóng.'
  },
  // 4. OQC - Chất lượng đầu ra (15%)
  {
    id: 'KPI-PRO-14',
    category: 'OQC - Chất lượng đầu ra',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Lỗi lọt kho thành phẩm',
    definition: 'Phát hiện xe lỗi bám trên bệ khi đã chuyển giao nhập kho thành phẩm KCS',
    unit: 'Tỉ lệ %',
    target: '<0.05%',
    actual: '0.02%',
    status: 'Đạt',
    details: 'Chỉ ghi nhận một vài trường hợp hở nhẹ khớp nhựa hãm bửng đã sửa tại chỗ.'
  },
  {
    id: 'KPI-PRO-15',
    category: 'OQC - Chất lượng đầu ra',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Sự cố lỗi trong vận hành sử dụng',
    definition: 'Số xe phát sinh điểm bất thường / Tổng quy mô sản lượng xe chạy thị trường',
    unit: 'Tỉ lệ %',
    target: '<0.5%',
    actual: '0.42%',
    status: 'Đạt',
    details: 'Khách hàng đánh giá hài lòng với khả năng vận hành êm ái của hệ thống DK Roma-X.'
  },
  {
    id: 'KPI-PRO-16',
    category: 'OQC - Chất lượng đầu ra',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Khiếu nại bất thường từ nhà phân phối',
    definition: 'Số vụ khiếu nại chất lượng xưởng gửi về trung tâm điều phối đại lý mỗi tháng',
    unit: 'Vụ việc',
    target: '<3 vụ/tháng',
    actual: '1 vụ/tháng',
    status: 'Đạt',
    details: 'Tháng này chỉ ghi nhận 1 trường hợp lỏng giắc còi sương mù ở lô xe gửi Nghệ An.'
  },
  {
    id: 'KPI-PRO-17',
    category: 'OQC - Chất lượng đầu ra',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Kiểm tra túc trực lắp ráp trên mỗi LSX phát hiện lỗi luồn dây còi',
    definition: 'Nhận thông tin khiếu nại kỹ thuật đại lý và phản hồi phương án kỹ thuật',
    unit: 'Tỉ lệ',
    target: '100%',
    actual: '100%',
    status: 'Đạt',
    details: 'Phương án xử lý kỹ thuật luôn được phản hồi bằng văn bản hướng dẫn chi tiết trong 24 giờ.'
  },
  {
    id: 'KPI-PRO-18',
    category: 'OQC - Chất lượng đầu ra',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Sự cố khuyết tật nghiêm trọng trên thị trường',
    definition: 'Lôi gãy gập khung gầm, cháy nổ IC nguồn hệ thống (Trọng số bắt buộc 0)',
    unit: 'Tỉ lệ %',
    target: '0%',
    actual: '0%',
    status: 'Đạt',
    details: 'Kiểm tra xung dòng cao KCS đầu ra kỹ lưỡng loại bỏ triệt để nguy cơ phóng điện dập tủ điện.'
  },
  // 5. Hệ thống & Hồ sơ (15%)
  {
    id: 'KPI-PRO-19',
    category: 'Hệ thống & Hồ sơ',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Tài liệu tiêu chuẩn chất lượng',
    definition: 'Các dòng xe xuất xưởng bắt buộc có sổ tay tiêu chuẩn chất lượng và Checklist KCS',
    unit: 'Tỉ lệ %',
    target: '100%',
    actual: '100%',
    status: 'Đạt',
    details: 'Đã hoàn tất sổ tay HDSD và lắp ráp chuẩn hóa của dòng xe mới DK V1.'
  },
  {
    id: 'KPI-PRO-20',
    category: 'Hệ thống & Hồ sơ',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Sáng kiến cải tiến chất lượng',
    definition: 'Mỗi model xe cải tiến ít nhất 1 lần/tháng. Đạt mục tiêu 12 lần cải tiến/năm cho sản phẩm chính',
    unit: 'Lần',
    target: '12',
    actual: '5',
    status: 'Theo dõi',
    details: 'Vừa hoàn chỉnh phương pháp bọc lót nén bầu sạc để triệt lổ rung chấn khi tải dốc.'
  },
  {
    id: 'KPI-PRO-21',
    category: 'Hệ thống & Hồ sơ',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Tiết kiệm chi phí chất lượng kém COPQ',
    definition: 'Tỷ lệ chi phí thiệt hại chất lượng hư hao do lỗi dây chuyền giảm thiểu so với kỳ trước',
    unit: 'Tỉ lệ %',
    target: '>=10%',
    actual: '12.4%',
    status: 'Đạt',
    details: 'Ghi nhận tiết giảm chi phí sửa chữa sườn bệ của chuỗi băng chuyền Model DK Gogo.'
  },
  {
    id: 'KPI-PRO-22',
    category: 'Hệ thống & Hồ sơ',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Huấn luyện đào tạo KCS đạt chuẩn',
    definition: 'Số lượng nhân sự được đào tạo kiểm nhận và bắt lỗi linh kiện chính xác',
    unit: 'Nhân sự',
    target: '4',
    actual: '4',
    status: 'Đạt',
    details: 'Nhân sự rà lỗi đã được trao chứng chỉ chất lượng nội bộ quý I.'
  },
  {
    id: 'KPI-PRO-23',
    category: 'Hệ thống & Hồ sơ',
    type: 'Mục tiêu hoạt động chuyên môn',
    groupWeight: 15,
    indicator: 'Lưu trữ hồ sơ nghiệm kiểm ISO',
    definition: 'Tỉ lệ lưu trữ biên bản kỹ thuật số hóa so với số lượt kiểm rà thực tế',
    unit: 'Tỉ lệ %',
    target: '100%',
    actual: '100%',
    status: 'Đạt',
    details: 'Cơ sở dữ liệu đám mây sao lưu an toàn hàng ngày tại DK Việt Nhật.'
  }
];
