import { PTSPTask } from './types';

const generateTasksForProject = (projId: string): PTSPTask[] => [
  // ================= Stage 1: Thống nhất cấu hình kỹ thuật =================
  {
    id: `ptsp-${projId}-1-1`,
    projectId: projId,
    stage: 1,
    stageName: "Thống nhất cấu hình kỹ thuật",
    itemCode: "1.1",
    name: "Nhập mẫu",
    description: "Nhập mẫu nguyên xe để thực hiện đánh giá tổng quan và đánh giá không gian hẹp, tham khảo ý kiến khách hàng",
    unit: "Xe",
    target: "2",
    executor: "Hương",
    cooperator: "Xuyến",
    startDate: "2026-06-01",
    endDate: "2026-06-09",
    duration: 8,
    progress: 100,
    result: "Ngày 19/11 - Mới nhập mẫu. Chậm kế hoạch 9 ngày",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-1-2`,
    projectId: projId,
    stage: 1,
    stageName: "Thống nhất cấu hình kỹ thuật",
    itemCode: "1.2",
    name: "Xây dựng hồ sơ sản phẩm",
    description: "Xây dựng bộ hồ sơ theo dõi phát triển đánh giá sản phẩm",
    unit: "Bộ",
    target: "1",
    executor: "Linh",
    cooperator: "Thao",
    startDate: "2026-06-05",
    endDate: "2026-06-12",
    duration: 7,
    progress: 80,
    result: "Đã xây dựng. Phần khung, động cơ thực hiện. Chưa có ảnh cát nét sản phẩm",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-1-3`,
    projectId: projId,
    stage: 1,
    stageName: "Thống nhất cấu hình kỹ thuật",
    itemCode: "1.3",
    name: "Đánh giá tĩnh",
    description: "Đánh giá xe ở trạng thái tĩnh, đánh giá ngoại quan, độ kín khít, kiểu dáng, các vị trí lắp nhựa,...",
    unit: "-",
    target: "-",
    executor: "PKD",
    cooperator: "Kỹ Thuật",
    startDate: "2026-06-10",
    endDate: "2026-06-15",
    duration: 5,
    progress: 40,
    result: "Hiện chưa chốt mẫu mặt nạ. Hương nhập thêm mẫu của nhà Trung Việt",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-1-4`,
    projectId: projId,
    stage: 1,
    stageName: "Thống nhất cấu hình kỹ thuật",
    itemCode: "1.4",
    name: "Trải nghiệm không gian hẹp",
    description: "Chạy thử xe trong không gian xưởng và quãng đường ngắn để đánh giá các tính năng trải nghiệm sử dụng.",
    unit: "-",
    target: "-",
    executor: "PKD",
    cooperator: "Kỹ Thuật",
    startDate: "2026-06-12",
    endDate: "2026-06-18",
    duration: 6,
    progress: 50,
    result: "Đã chạy 112km/ 3 lượt chạy thử. Từ ngày 26/11 Thực hiện chạy đường trường. PKD chưa đánh giá và chốt mặt nạ.",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-1-5`,
    projectId: projId,
    stage: 1,
    stageName: "Thống nhất cấu hình kỹ thuật",
    itemCode: "1.5",
    name: "Tháo dỡ đánh giá linh kiện",
    description: "Tháo dỡ linh kiện để đánh giá bên trong (động cơ, IC, dây dẫn, đèn pha…) kết hợp xây dựng sơ bộ quy trình lắp ráp và định mức linh kiện.",
    unit: "-",
    target: "-",
    executor: "Thao",
    cooperator: "Tân, Việt",
    startDate: "2026-06-15",
    endDate: "2026-06-22",
    duration: 7,
    progress: 30,
    result: "Chưa thực hiện. Đợi xe mẫu trùng việt để đánh giá ngoại quan song song mới thực hiện chốt kiểu dáng sau mới thực hiện tháo linh kiện",
    isCritical: true,
    link: ""
  },

  // ================= Stage 2: Xây dựng tiêu chuẩn chọn mẫu =================
  {
    id: `ptsp-${projId}-2-1`,
    projectId: projId,
    stage: 2,
    stageName: "Xây dựng tiêu chuẩn chọn mẫu",
    itemCode: "2.1",
    name: "Kiểm tra Kỹ thuật (So với yêu cầu)",
    description: "Kiểm tra sản phẩm (linh kiện) đảm bảo đúng mẫu yêu cầu so với tiêu chuẩn đặt ra ( ngoại quan, tính năng, kích thước, chất lượng).",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Thao",
    startDate: "2026-06-20",
    endDate: "2026-06-25",
    duration: 5,
    progress: 10,
    result: "Đang thực hiện",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-2-2`,
    projectId: projId,
    stage: 2,
    stageName: "Xây dựng tiêu chuẩn chọn mẫu",
    itemCode: "2.2",
    name: "Kiểm tra Lắp thử",
    description: "Lắp lại mẫu để đánh giá tình trạng quá trình lắp. Đảm bảo lắp vừa khít với tổng thể sản phẩm. Không bị cấn, hở, lỗi gây ảnh hưởng đến sự đồng bộ của sản phẩm",
    unit: "-",
    target: "-",
    executor: "Tân",
    cooperator: "Thao",
    startDate: "2026-06-23",
    endDate: "2026-06-28",
    duration: 5,
    progress: 0,
    result: "Chờ phối hợp lắp thử",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-2-3`,
    projectId: projId,
    stage: 2,
    stageName: "Xây dựng tiêu chuẩn chọn mẫu",
    itemCode: "2.3",
    name: "Kiểm tra Chức năng & Độ bền (Chạy thử)",
    description: "",
    unit: "Km",
    target: "1500",
    executor: "Thao",
    cooperator: "Việt, Phấn",
    startDate: "2026-06-25",
    endDate: "2026-07-05",
    duration: 10,
    progress: 0,
    result: "Chờ lắp ráp hoàn tất sườn xe mới chạy thử nghiệm đường trường",
    isCritical: true,
    link: ""
  },

  // ================= Stage 3: Thử nghiệm, trải nghiệm sử dụng =================
  {
    id: `ptsp-${projId}-3-1`,
    projectId: projId,
    stage: 3,
    stageName: "Thử nghiệm, trải nghiệm sử dụng",
    itemCode: "3.1",
    name: "Chuẩn bị Kịch bản Trải nghiệm",
    description: "Nhận sản phẩm: Lấy một sản phẩm hoàn chỉnh (đã qua FQC).Sản phẩm dùng để thử nghiệm phải là một sản phẩm hoàn chỉnh 100%, đã được kiểm tra đạt về mọi mặt. Với tư cách là người sử dụng",
    unit: "Xe",
    target: "1",
    executor: "Linh",
    cooperator: "Thao, Việt, Phấn, Tân",
    startDate: "2026-06-26",
    endDate: "2026-06-30",
    duration: 4,
    progress: 0,
    result: "Chưa biên tập kịch bản",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-3-2`,
    projectId: projId,
    stage: 3,
    stageName: "Thử nghiệm, trải nghiệm sử dụng",
    itemCode: "3.2",
    name: "Thực hiện Trải nghiệm (Sử dụng thực tế)",
    description: "Mục tiêu: Sử dụng sản phẩm như thói quen hàng ngày.\nHành động:\nLắp ráp & Khởi động: Thử lắp gương, sạc lần đầu tiên, cắm chìa khóa (có dễ cắm không?).\nVận hành cơ bản: Dắt xe (có nặng không?), để chân (có thoải mái?), bật/tắt đèn, xi-nhan (nút bấm có tiện tay không?).\nTình huống thực tế:\nThử đi chợ: Móc treo đồ có dễ treo không? Cốp xe có dễ mở, có đủ rộng để mũ bảo hiểm không?\nThử đi trời tối: Đèn có đủ sáng đường không? Màn hình có bị chói mắt không?\nThử đi trời mưa/đường xấu: Xe có bị trơn trượt? Giảm xóc có quá cứng không?\nThử sạc: Dây sạc có đủ dài? Cắm sạc có dễ dàng không?",
    unit: "Ngày",
    target: "10",
    executor: "Linh",
    cooperator: "Thao, Việt, Phấn, Tân, Diệm, Thế, Chinh",
    startDate: "2026-07-01",
    endDate: "2026-07-11",
    duration: 10,
    progress: 0,
    result: "Chờ khởi động kịch bản",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-3-3`,
    projectId: projId,
    stage: 3,
    stageName: "Thử nghiệm, trải nghiệm sử dụng",
    itemCode: "3.3",
    name: "Ghi nhận Phản hồi (Báo cáo Trải nghiệm)",
    description: "Mục tiêu: Ghi lại tất cả các điểm \"khó chịu\" (Pain Points).\nHành động:\nGhi lại : Các lỗi kỹ thuật (nếu còn).\nGhi điểm bất tiện): Ghi lại mọi thứ gây khó khăn. Ví dụ: \"Nút còi quá xa ngón tay, phải rướn\", \"Chân chống phụ quá yếu\", \"yên xe cứng ngồi lâu mỏi\".\nGhi nhận Góp ý: Đề xuất ý tưởng cải tiến. Ví dụ: \"Nên thêm chế độ mở yên điện\". \"Thêm tính năng ngắt điện chân chống\"...\nHoàn thành báo cáo trải nghiệm gửi cho R&D.",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Thao, Việt, Phấn, Tân, Diệm, Thế, Chinh",
    startDate: "2026-07-12",
    endDate: "2026-07-15",
    duration: 3,
    progress: 0,
    result: "Chờ thực hiện tổng hợp",
    isCritical: false,
    link: ""
  },

  // ================= Stage 4: Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn =================
  {
    id: `ptsp-${projId}-4-1`,
    projectId: projId,
    stage: 4,
    stageName: "Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn",
    itemCode: "4.1",
    name: "Xây dựng bảng màu chủ đạo theo nhận diện DKBike",
    description: "Làm bảng màu và phối màu theo chủ đề yêu cầu. Và xu hướng thị trường",
    unit: "-",
    target: "-",
    executor: "Hương",
    cooperator: "Nani",
    startDate: "2026-07-10",
    endDate: "2026-07-14",
    duration: 4,
    progress: 0,
    result: "Chờ phối hợp thiết kế phối màu",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-4-2`,
    projectId: projId,
    stage: 4,
    stageName: "Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn",
    itemCode: "4.2",
    name: "Đặt tên SP + Thiết kế tem",
    description: "Làm tem nhãn theo tên sản phẩm. Và thiết kế logo",
    unit: "-",
    target: "-",
    executor: "Hương",
    cooperator: "Hạnh",
    startDate: "2026-07-15",
    endDate: "2026-07-19",
    duration: 4,
    progress: 0,
    result: "Đang dựng phác thảo tem",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-4-3`,
    projectId: projId,
    stage: 4,
    stageName: "Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn",
    itemCode: "4.3",
    name: "Đề xuất vật liệu sơn",
    description: "Tiêu chuẩn chất lượng sơn, và lựa chọn tìm kiếm NCC sơn phụ",
    unit: "-",
    target: "-",
    executor: "Hương",
    cooperator: "Xuyến",
    startDate: "2026-07-20",
    endDate: "2026-07-25",
    duration: 5,
    progress: 0,
    result: "Đang liên hệ NCC sơn dập mẫu",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-4-4`,
    projectId: projId,
    stage: 4,
    stageName: "Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn",
    itemCode: "4.4",
    name: "Cập nhật thông số sau test",
    description: "Cập nhập hồ sơ thông tin sau khi test và trải nghiệm sản phẩm - Cập nhập các vấn đề thông tin thay đổi. Các vấn đề cập nhật liên tục",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Thao",
    startDate: "2026-07-26",
    endDate: "2026-07-30",
    duration: 4,
    progress: 0,
    result: "Chờ thông số trải nghiệm kết thúc",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-4-5`,
    projectId: projId,
    stage: 4,
    stageName: "Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn",
    itemCode: "4.5",
    name: "Gửi yêu cầu hiệu chỉnh tới NCC",
    description: "Gửi NCC các yêu cầu điều chỉnh, và các vấn đề trong quá trình sử dụng cần cải tiến và điều chỉnh phù hợp với yêu cầu .",
    unit: "-",
    target: "-",
    executor: "Thao",
    cooperator: "Xuyến",
    startDate: "2026-07-31",
    endDate: "2026-08-04",
    duration: 4,
    progress: 0,
    result: "Chờ tổng hợp danh sách lỗi dập mẫu",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-4-6`,
    projectId: projId,
    stage: 4,
    stageName: "Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn",
    itemCode: "4.6",
    name: "Kiểm tra lại mẫu hiệu chỉnh",
    description: "Kiểm tra lại các linh kiện sau khi chốt mẫu (tem, thông số, kích thước, trạng thái…) để thực hiện làm đăng kiểm",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Thao, Cương",
    startDate: "2026-08-05",
    endDate: "2026-08-10",
    duration: 5,
    progress: 0,
    result: "Chờ mẫu sửa đổi phản hồi từ nhà cung cấp",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-4-7`,
    projectId: projId,
    stage: 4,
    stageName: "Hiệu chỉnh kỹ thuật & chốt mẫu chuẩn",
    itemCode: "4.7",
    name: "Chốt mẫu & Nhập linh kiện mẫu chuẩn để làm đăng kiểm",
    description: "Nhập linh kiện chính để thực hiện làm thử nghiệm (vành, động cơ, IC, Khung, đèn pha…)",
    unit: "-",
    target: "-",
    executor: "Cương",
    cooperator: "Xuyến",
    startDate: "2026-08-11",
    endDate: "2026-08-16",
    duration: 5,
    progress: 0,
    result: "Chờ chốt mẫu 4.6",
    isCritical: true,
    link: ""
  },

  // ================= Stage 5: Đăng kiểm thử nghiệm =================
  {
    id: `ptsp-${projId}-5-1`,
    projectId: projId,
    stage: 5,
    stageName: "Đăng kiểm thử nghiệm",
    itemCode: "5.1",
    name: "Thử nghiệm đăng kiểm linh kiện",
    description: "Mang linh kiện đi làm thử nghiệm tại cục đăng kiểm",
    unit: "-",
    target: "-",
    executor: "Cương",
    cooperator: "Tiến",
    startDate: "2026-08-17",
    endDate: "2026-08-25",
    duration: 8,
    progress: 0,
    result: "Chờ chuẩn bị mẫu chi tiết",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-5-2`,
    projectId: projId,
    stage: 5,
    stageName: "Đăng kiểm thử nghiệm",
    itemCode: "5.2",
    name: "Thử nghiệm toàn xe - An toàn",
    description: "Mang xe nguyên chiếc đồng bộ để mang đi làm thử nghiệm tại cục\nThực hiện thử nghiệm năng lượng sau 10 ngày so với thử nghiệm an toàn\nThời gian thử nghiệm chưa bao gồm ngày nghỉ theo lịch hành chính",
    unit: "-",
    target: "-",
    executor: "Cương",
    cooperator: "Việt, Thao, Phấn",
    startDate: "2026-08-26",
    endDate: "2026-09-04",
    duration: 9,
    progress: 0,
    result: "Chờ lịch từ cục Đăng kiểm",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-5-3`,
    projectId: projId,
    stage: 5,
    stageName: "Đăng kiểm thử nghiệm",
    itemCode: "5.3",
    name: "Thử nghiệm toàn xe - Năng lượng",
    description: "",
    unit: "-",
    target: "-",
    executor: "Cương",
    cooperator: "Việt, Thao, Phấn",
    startDate: "2026-09-05",
    endDate: "2026-09-12",
    duration: 7,
    progress: 0,
    result: "Chờ thực hiện đo lường năng lượng",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-5-4`,
    projectId: projId,
    stage: 5,
    stageName: "Đăng kiểm thử nghiệm",
    itemCode: "5.4",
    name: "Cấp CGN kiểu loại xe thành phẩm",
    description: "Cấp giấy chứng nhận kiểu loại đủ điều kiện triển khai lắp ráp và bán xe ra thị trường",
    unit: "-",
    target: "-",
    executor: "Cương",
    cooperator: "-",
    startDate: "2026-09-13",
    endDate: "2026-09-20",
    duration: 7,
    progress: 0,
    result: "Chờ văn bản quyết định",
    isCritical: true,
    link: ""
  },

  // ================= Stage 6: Cập nhật hồ sơ sản phẩm & Đào tạo =================
  {
    id: `ptsp-${projId}-6-1`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.1",
    name: "Thông tin chung sản phẩm",
    description: "Cập nhập các thông tin chung về sản phẩm, kích thước, thông số (theo kết quả thử nghiệm của cục đăng kiểm)",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Thao",
    startDate: "2026-09-21",
    endDate: "2026-09-24",
    duration: 3,
    progress: 0,
    result: "Chờ thông số đăng kiểm mẫu chính xác",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-6-2`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.2",
    name: "Quá trình phát triển sản phẩm",
    description: "Tổng hợp và đánh giá tổng các vấn đề trong quá trình phát triển sản phẩm. Các điểm lỗi cần chú ý kiểm tra trước khi nhập kho, lắp ráp",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Thao",
    startDate: "2026-09-25",
    endDate: "2026-09-29",
    duration: 4,
    progress: 0,
    result: "Chờ báo cáo tổng duyệt R&D",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-6-3`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.3",
    name: "Định mức LK",
    description: "Cập nhập định mức linh kiện, dựa trên các linh kiện đồng bộ (Kích thước ốc, số lượng chủng loại…)",
    unit: "-",
    target: "-",
    executor: "Xuyến",
    cooperator: "Thao",
    startDate: "2026-09-30",
    endDate: "2026-10-04",
    duration: 4,
    progress: 0,
    result: "Chờ dữ liệu BOM chính xác",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-6-4`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.4",
    name: "Tiêu chuẩn kiểm tra LK",
    description: "Cập nhập các tiêu chuẩn kiểm tra chất lượng linh kiện",
    unit: "-",
    target: "-",
    executor: "Thao",
    cooperator: "Việt, Phấn",
    startDate: "2026-10-05",
    endDate: "2026-10-09",
    duration: 4,
    progress: 0,
    result: "Chờ dữ liệu đo lường kỹ thuật",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-6-5`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.5",
    name: "Hướng dẫn lắp ráp + tiêu chuẩn kiểm tra công đoạn",
    description: "Xây dựng quy trình hướng dẫn lắp ráp từng công đoạn và kiểm tra chất lượng công đoạn",
    unit: "-",
    target: "-",
    executor: "Tân",
    cooperator: "Thể, Chinh, Lân",
    startDate: "2026-10-10",
    endDate: "2026-10-15",
    duration: 5,
    progress: 0,
    result: "Chờ dựng bản nháp SOP chuyền mẫu",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-6-6`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.6",
    name: "Đào tạo tổng quan chung sản phẩm",
    description: "Đào tạo chung về sản phẩm cho MKT & PKD",
    unit: "-",
    target: "-",
    executor: "Thao",
    cooperator: "Linh",
    startDate: "2026-10-16",
    endDate: "2026-10-18",
    duration: 2,
    progress: 0,
    result: "Chờ lên lịch họp nội bộ",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-6-7`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.7",
    name: "Đào tạo lắp ráp, chất lượng",
    description: "Đào tạo hướng dẫn lắp ráp trên dây chuyền",
    unit: "-",
    target: "-",
    executor: "Tân",
    cooperator: "Thể, Thao",
    startDate: "2026-10-19",
    endDate: "2026-10-21",
    duration: 2,
    progress: 0,
    result: "Chờ tổ chức đào tạo đầu dây chuyền",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-6-8`,
    projectId: projId,
    stage: 6,
    stageName: "Cập nhật hồ sơ sản phẩm & Đào tạo",
    itemCode: "6.8",
    name: "Hướng dẫn đại lý",
    description: "Hướng dẫn đại lý về sản phẩm, sử dụng, lắp AQ, tính năng…",
    unit: "-",
    target: "-",
    executor: "Diệm",
    cooperator: "Linh",
    startDate: "2026-10-22",
    endDate: "2026-10-25",
    duration: 3,
    progress: 0,
    result: "Chờ biên tập sổ tay kỹ thuật",
    isCritical: false,
    link: ""
  },

  // ================= Stage 7: Nhập hàng & Sản xuất lắp ráp =================
  {
    id: `ptsp-${projId}-7-1`,
    projectId: projId,
    stage: 7,
    stageName: "Nhập hàng & Sản xuất lắp ráp",
    itemCode: "7.1",
    name: "Nhập lô hàng lắp mẫu",
    description: "Nhập mẫu lô 10 ~ 20 xe để thực hiện lắp ráp và đánh giá chất lượng dựng bộ lô hàng",
    unit: "Xe",
    target: "15",
    executor: "Xuyến",
    cooperator: "Đạo",
    startDate: "2026-10-26",
    endDate: "2026-10-31",
    duration: 5,
    progress: 0,
    result: "Chờ phê chuẩn vận đơn NCC",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-7-2`,
    projectId: projId,
    stage: 7,
    stageName: "Nhập hàng & Sản xuất lắp ráp",
    itemCode: "7.2",
    name: "Chuẩn bị Sản xuất Mẫu",
    description: "Nhận tài liệu: Tập hợp đầy đủ hồ sơ kỹ thuật từ R&D (Tiêu chuẩn kỹ thuật, Hướng dẫn lắp ráp tạm thời).\nChuẩn bị Vật tư: Đảm bảo 100% linh kiện, vật tư (đã được phê duyệt mẫu) được tập kết đầy đủ.\nChuẩn bị Thiết bị, Dụng cụ: Lắp đặt, kiểm tra các gá lắp, dụng cụ phục vụ cho lắp ráp\nHọp Phổ biến: Tổ chức họp (kick-off) với các bộ phận liên quan (Kỹ thuật, R&D, Sản xuất, QC) để thống nhất kế hoạch, mục tiêu, và các điểm cần theo dõi.",
    unit: "Xe",
    target: "15",
    executor: "Linh",
    cooperator: "Thao, Tân, Long, Thể, Chinh, Việt, Phấn",
    startDate: "2026-11-01",
    endDate: "2026-11-05",
    duration: 5,
    progress: 0,
    result: "Chờ vật tư lô hàng mẫu tề tựu",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-7-3`,
    projectId: projId,
    stage: 7,
    stageName: "Nhập hàng & Sản xuất lắp ráp",
    itemCode: "7.3",
    name: "Thực hiện Lắp ráp Lô Mẫu",
    description: "Tiến hành lắp ráp: Công nhân thực hiện lắp ráp dưới sự giám sát chặt chẽ.\nƯu tiên: Lắp ráp chậm, cẩn thận, làm đúng theo hướng dẫn. Không chạy theo năng suất, mà chạy để tìm vấn đề.\nĐội ngũ giám sát: Kỹ sư (R&D, Kỹ thuật) và QA/QC phải có mặt 100% thời gian trên chuyến",
    unit: "Xe",
    target: "15",
    executor: "Thao",
    cooperator: "Tân",
    startDate: "2026-11-06",
    endDate: "2026-11-12",
    duration: 6,
    progress: 0,
    result: "Chờ triển khai gáp chuyền Pilot",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-7-4`,
    projectId: projId,
    stage: 7,
    stageName: "Nhập hàng & Sản xuất lắp ráp",
    itemCode: "7.4",
    name: "Giám sát & Ghi nhận Vấn đề",
    description: "Mục tiêu: Ghi lại TẤT CẢ các điểm không hợp lệ phát sinh trong quá trình lắp.\nHành động: Dùng \"Phiếu Ghi nhận Vấn đề\" để ghi lại ngay lập tức, ví dụ:\nLỗi Thiết kế: \"Linh kiện A bị cấn linh kiện B\", \"Bản vẽ thiếu ốc\".\nLỗi Quy trình: \"Thao tác này quá khó làm\", \"Thứ tự lắp ráp bị ngược, phải tháo ra lắp lại\".\nLỗi Gá/Dụng cụ: \"Gá (jig) bị kẹt\", \"Súng siết lực không vươn tới được vị trí ốc\".\nLỗi Vật tư: \"Linh kiện bị sai lệch so với mẫu\".",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Thao, Tân",
    startDate: "2026-11-13",
    endDate: "2026-11-16",
    duration: 3,
    progress: 0,
    result: "Chờ trực tuyến ghi nhận",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-7-5`,
    projectId: projId,
    stage: 7,
    stageName: "Nhập hàng & Sản xuất lắp ráp",
    itemCode: "7.5",
    name: "Họp Tổng kết & Báo cáo",
    description: "Họp nhanh: Tổ chức họp ngay sau khi kết thúc lô sản xuất mẫu.\nTổng hợp vấn đề: Xem xét lại toàn bộ các vấn đề đã ghi nhận ở trên.\nPhân công hành động: Phân công rõ ràng:\nR&D: Phải sửa lại thiết kế, bản vẽ.\nKỹ thuật/Sản xuất: Phải sửa lại quy trình, làm lại gá.\nLập báo cáo: Ra \"Báo cáo Kết quả Sản xuất Mẫu\", kết luận sản phẩm đã \"Sẵn sàng\" hay \"Chưa sẵn sàng\" cho sản xuất hàng loạt",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "Xuyến, Thao",
    startDate: "2026-11-17",
    endDate: "2026-11-20",
    duration: 3,
    progress: 0,
    result: "Chờ kết quả lô Pilot",
    isCritical: true,
    link: ""
  },
  {
    id: `ptsp-${projId}-7-6`,
    projectId: projId,
    stage: 7,
    stageName: "Nhập hàng & Sản xuất lắp ráp",
    itemCode: "7.6",
    name: "Nhập lô hàng đồng loạt",
    description: "Sau khi có báo cáo đánh giá tình trạng lô mẫu thực hiện nhập số lượng theo kế hoạch kinh doanh để sản xuất đồng loạt.\nVới điều kiện đã xử lý các vấn đề mẫu",
    unit: "BLK",
    target: "-",
    executor: "Xuyến",
    cooperator: "Hương",
    startDate: "2026-11-21",
    endDate: "2026-11-27",
    duration: 6,
    progress: 0,
    result: "Chờ quyết định hoàn thành lô mẫu",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-7-7`,
    projectId: projId,
    stage: 7,
    stageName: "Nhập hàng & Sản xuất lắp ráp",
    itemCode: "7.7",
    name: "Triển khai sản xuất đồng loại",
    description: "Dựa trên báo cáo kết quả sản xuất lô nhỏ thực hiện sản xuất đồng loạt phục vụ nhu cầu kinh doanh",
    unit: "Xe",
    target: "100",
    executor: "Tân",
    cooperator: "Thao",
    startDate: "2026-11-28",
    endDate: "2026-12-10",
    duration: 12,
    progress: 0,
    result: "Chờ chuyển giao hoàn công sản xuất đại trà",
    isCritical: true,
    link: ""
  },

  // ================= Stage 8: Sau bán hàng (Theo dõi phản ứng thị trường) =================
  {
    id: `ptsp-${projId}-8-1`,
    projectId: projId,
    stage: 8,
    stageName: "Sau bán hàng (Theo dõi phản ứng thị trường)",
    itemCode: "8.1",
    name: "Lắng nghe Khách hàng",
    description: "Mục tiêu: Thu thập phản hồi trực tiếp từ người dùng.\nHành động:\nQuét Mạng xã hội: Đọc bình luận, bài đăng trong các hội nhóm (Facebook, Zalo), diễn đàn về sản phẩm.\nKiểm tra Kênh Bán hàng: Xem các đánh giá (reviews) trên sàn thương mại điện tử (Shopee, Tiki...).\nTổng hợp từ sale admin: Nhận báo cáo hàng ngày từ bộ phận Chăm sóc khách hàng về các khiếu nại hoặc câu hỏi thường gặp liên quan đến sản phẩm mới.",
    unit: "-",
    target: "-",
    executor: "CSKH",
    cooperator: "QLCL",
    startDate: "2026-12-11",
    endDate: "2026-12-20",
    duration: 9,
    progress: 0,
    result: "Chờ triển khai sau bán hàng",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-8-2`,
    projectId: projId,
    stage: 8,
    stageName: "Sau bán hàng (Theo dõi phản ứng thị trường)",
    itemCode: "8.2",
    name: "Theo dõi động thái đối thủ",
    description: "Xem đối thủ cạnh tranh \"phản ứng\" như thế nào với sản phẩm mới của ta",
    unit: "-",
    target: "-",
    executor: "PKD",
    cooperator: "QLCL",
    startDate: "2026-12-15",
    endDate: "2026-12-25",
    duration: 10,
    progress: 0,
    result: "Chờ báo cáo thị trường",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-8-3`,
    projectId: projId,
    stage: 8,
    stageName: "Sau bán hàng (Theo dõi phản ứng thị trường)",
    itemCode: "8.3",
    name: "Theo dõi Truyền thông & Báo chí",
    description: "Mục tiêu: Xem các bên thứ ba (báo chí, người nổi tiếng) đang nói gì.\nHành động:\nTheo dõi các bài báo, bài review từ các trang tin công nghệ, xe cộ.\nXem các video \"đập hộp\", \"đánh giá\" từ KOCs/KOLs (Influencers).",
    unit: "-",
    target: "-",
    executor: "MKT",
    cooperator: "QLCL",
    startDate: "2026-12-18",
    endDate: "2026-12-28",
    duration: 10,
    progress: 0,
    result: "Chờ thu thập tin tức truyền thông",
    isCritical: false,
    link: ""
  },
  {
    id: `ptsp-${projId}-8-4`,
    projectId: projId,
    stage: 8,
    stageName: "Sau bán hàng (Theo dõi phản ứng thị trường)",
    itemCode: "8.4",
    name: "Tổng hợp & Báo cáo Nhanh",
    description: "Mục tiêu: Biến các thông tin trên thành báo cáo có giá trị.\nHành động:\nLập báo cáo (thường là hàng tuần) tóm tắt các điểm chính.\nPhân loại: Các điểm \"Khen\" (được yêu thích), các điểm \"Chê\" (bị phàn nàn nhiều nhất).\nCảnh báo khẩn: Nếu phát hiện một lỗi nghiêm trọng hoặc một khủng hoảng truyền thông, phải báo cáo ngay lập tức cho R&D và Ban Lãnh Đạo.",
    unit: "-",
    target: "-",
    executor: "Linh",
    cooperator: "R&D, Thao",
    startDate: "2026-12-22",
    endDate: "2026-12-31",
    duration: 9,
    progress: 0,
    result: "Chờ tổng hợp tuần hỏa tốc",
    isCritical: true,
    link: ""
  }
];

export const INITIAL_PTSP_TASKS: PTSPTask[] = [
  ...generateTasksForProject("PRJ-VOLTv2"),
  ...generateTasksForProject("volt-v2-demo")
];
